# Generated by Django 4.2.7 on 2023-12-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksapp', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('dob', models.IntegerField()),
                ('phnno', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('password', models.IntegerField()),
                ('cpassword', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
