# Generated by Django 4.2.7 on 2023-12-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksapp', '0004_remove_user_cpassword_alter_user_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phnno',
            field=models.IntegerField(max_length=250),
        ),
    ]
