# Generated by Django 4.2.7 on 2023-12-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banksapp', '0006_alter_user_phnno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bank',
        ),
    ]
