# Generated by Django 3.2.18 on 2023-12-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksapp', '0007_delete_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default='F', max_length=1),
        ),
    ]
