# Generated by Django 3.2.18 on 2024-01-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksapp', '0009_auto_20231228_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250, null=True)),
                ('last_name', models.CharField(max_length=250, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phnno', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
