# Generated by Django 3.2.18 on 2024-01-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksapp', '0010_auto_20240109_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=250)),
                ('district', models.CharField(choices=[('Idukki', 'Idukki'), ('Eranakulam', 'Ernakulam'), ('Thrissur', 'Thrissur'), ('Kottayam', 'Kottayam')], max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='user1',
            name='ac_type',
            field=models.CharField(choices=[('S', 'Savings Account'), ('C', 'Current Account')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user1',
            name='materials',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
