# Generated by Django 3.2.18 on 2024-01-09 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banksapp', '0011_auto_20240109_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banksapp.branchs'),
        ),
        migrations.AlterField(
            model_name='branchs',
            name='branch',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
