# Generated by Django 3.2.18 on 2024-01-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksapp', '0015_auto_20240110_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='district',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
