# Generated by Django 3.2.18 on 2024-01-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksapp', '0016_alter_user1_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='branch',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
