# Generated by Django 3.2.18 on 2024-01-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksapp', '0017_alter_user1_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchs',
            name='district',
            field=models.CharField(choices=[('Idukki', 'Idukki'), ('Eranakulam', 'Ernakulam'), ('Thrissur', 'Thrissur'), ('Kottayam', 'Kottayam'), ('Kozhikode', 'Kozhikode')], max_length=250),
        ),
    ]
