# Generated by Django 3.2.18 on 2024-01-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksapp', '0020_auto_20240125_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='materials',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
