# Generated by Django 3.2.18 on 2024-01-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banksapp', '0023_auto_20240125_1316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Materials',
        ),
    ]
