# Generated by Django 3.2.18 on 2024-01-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksapp', '0024_delete_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='materials',
            field=models.CharField(max_length=200),
        ),
    ]
