# Generated by Django 3.2.18 on 2024-01-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksapp', '0025_alter_user1_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='ac_type',
            field=models.CharField(choices=[('S', 'Savings Account'), ('C', 'Current Account')], max_length=1),
        ),
    ]
