# Generated by Django 3.2.18 on 2024-01-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksapp', '0026_alter_user1_ac_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
