# Generated by Django 3.2.18 on 2024-01-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banksapp', '0028_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user1',
            name='password',
        ),
    ]
